ELEMENT_ROTATION = 'rotation'
ELEMENT_LIFT = 'lift'
ELEMENT_ARM = 'arm'
ELEMENT_GRIPPER = 'gripper'

MANIPULATOR_ELEMENTS = (
    ELEMENT_ROTATION,
    ELEMENT_LIFT,
    ELEMENT_ARM,
    ELEMENT_GRIPPER,
)
